ELEMENTS = {

    "EXECUTION TASK ELEMENT": """<tr><td style="padding: 15px 20px;"><span style="display: inline-block; width: 22px; height: 22px; background-color: #1e7e34; border-radius: 50%; color: #ffffff; text-align: center; line-height: 22px; font-size: 12px; font-weight: bold; margin-right: 10px;">✓</span><span style="font-size: 16px; color: #1a1c1e;">{{{!EXECUTION TASK}}}</span></td></tr>""",

    "UPCOMING EXAM ELEMENT": """<tr><td style="padding: 20px;"><table role="presentation" border="0" cellpadding="0" cellspacing="0" width="100%"><tr><td class="mobile-stack" align="left" style="font-size: 18px; font-weight: 700; color: #c53030;">{{{!UPCOMING EXAM NAME}}}</td><td class="mobile-stack" align="right"><span class="date-badge" style="background-color: #fc8181; color: #ffffff; padding: 4px 12px; border-radius: 6px; font-size: 12px; font-weight: 700;">{{{!UPCOMING EXAM DATE}}}</span></td></tr><tr><td colspan="2" style="padding-top: 10px; font-size: 15px; line-height: 1.5; color: #742a2a;">{{{!UPCOMING EXAM DESCRIPTION}}}</td></tr></table></td></tr>""",

    "APPLICATION DEADLINE ELEMENT": """<tr style="background:#fff8e1; border-bottom:1px solid #f3e3c2;"><td width="6" style="background:#f59e0b;"></td><td style="padding:14px; color: #1a1c1e;"><strong>{{{!DEADLINE APPLICATION EXAM NAME}}}</strong></td><td class="mobile-right-align" style="padding:14px; text-align:right; color: #1a1c1e;">{{{!DEADLINE APPLICATION EXAM DATE}}}<span style="background:#f59e0b; color:#ffffff; font-size:11px; padding:3px 8px; border-radius:12px; margin-left:8px; display: inline-block; font-weight: bold;">DEADLINE</span></td></tr>""",

    "APPLICATION OPENING ELEMENT": """<tr style="background:#f3f4f6;"><td width="6" style="background:#16a34a;"></td><td style="padding:14px; color: #1a1c1e;"><strong>{{{!UPCOMING APPLICATION EXAM NAME}}}</strong></td><td class="mobile-right-align" style="padding:14px; text-align:right; color: #1a1c1e;">{{{!UPCOMING APPLICATION EXAM DATE}}}<span style="background:#16a34a; color:#ffffff; font-size:11px; padding:3px 8px; border-radius:12px; margin-left:8px; display: inline-block; font-weight: bold;">OPENING</span></td></tr>"""
}